version: '3.9'

services:

  # Node
  node:
    container_name: quiz-game_node
    restart: always
    networks:
      - default
      - nginx
    build:
      context: .
      network: default
    ports:
      - "3000:3000"

networks:
  nginx:
    external: true